
package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
             // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path = "/add") // Map ONLY GET Requests
  public String addNewUser(@ModelAttribute Candidate candidate, Model model) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    userRepository.save(candidate);
    model.addAttribute("candidates", userRepository.findAll());
    return "candidates";
  }

  @GetMapping("/add")
  public String addForm(Model model) {
    model.addAttribute("candidate", new Candidate("1", "2", "3", "4"));
    return "add";
  }

  @GetMapping(path = "/all")
  public String getAllCandidates(Model model) {
    model.addAttribute("candidates", userRepository.findAll());
    return "candidates";
  }

  @GetMapping(path = "")
  public String index() {
    return "index";
  }

  @GetMapping("/menu")
  public String getMenu() {
    return "menu.html";
  }

}
